services:

  identity-link-core:
    container_name: identity-link-core
    image: ghcr.io/sgoranov/identity-link-core:1.0.0
    environment:
      CONSENT_SCREEN_ENABLED: true
      LOGIN_TWO_FA_ENABLED: true
      TWO_FA_INDEX_ENDPOINT: https://${DOMAIN_NAME}/2fa/2fa/verify/{id}
      RESET_PASSWORD_URL: https://${DOMAIN_NAME}/users/reset-password/{id}
    depends_on:
      identity-link-database-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/api/v1/ping" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - identity-link-network

  identity-link-db-users:
    container_name: identity-link-db-users
    image: ghcr.io/sgoranov/identity-link-db-users:1.0.0
    environment:
      RESET_PASSWORD_REDIRECT_URL: https://${DOMAIN_NAME}/login/password/{id}
      FEATURE_RESET_PASSWORD_ENABLED: true
      FEATURE_PASSWORD_VALIDATION_ENABLED: true
    depends_on:
      identity-link-database-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9001/api/v1/ping" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - identity-link-network

  identity-link-db-clients:
    container_name: identity-link-db-clients
    image: ghcr.io/sgoranov/identity-link-db-clients:1.0.0
    depends_on:
      identity-link-database-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9002/api/v1/ping" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - identity-link-network

  identity-link-2fa:
    container_name: identity-link-2fa
    image: ghcr.io/sgoranov/identity-link-2fa:1.0.0
    environment:
      TWO_FA_REDIRECT_URI: https://${DOMAIN_NAME}/login/2fa
    depends_on:
      identity-link-database-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9003/api/v1/ping" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - identity-link-network

  identity-link-bff:
    container_name: identity-link-bff
    image: ghcr.io/sgoranov/identity-link-bff:1.0.0
    environment:
      OIDC_WELL_KNOWN_URL: https://${DOMAIN_NAME}/.well-known/openid-configuration
      POST_LOGIN_REDIRECT_URL: https://${DOMAIN_NAME}/admin-console
      POST_LOGOUT_REDIRECT_URL: https://${DOMAIN_NAME}/admin-console/logout-success
      PROXY_SERVICE_BASE_URLS: "{\"users\":\"https://${DOMAIN_NAME}/users\",\"clients\":\"https://${DOMAIN_NAME}/clients\"}"
    networks:
      - identity-link-network

  identity-link-console:
    container_name: identity-link-console
    image: ghcr.io/sgoranov/identity-link-console:1.0.1
    environment:
      VITE_MAX_USER_GROUPS: 20
      VITE_MAX_CLIENT_GROUPS: 20
      VITE_ADMINISTRATOR_GROUP: administrator
      VITE_DEFAULT_PAGE_SIZE: 10
      VITE_BFF_BASE_URL: https://${DOMAIN_NAME}/bff
    depends_on:
      - identity-link-bff
    networks:
      - identity-link-network

  identity-link-proxy:
    container_name: identity-link-proxy
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    command:
      - /bin/sh
      - -c
      - |
        set -eux

        envsubst '$$DOMAIN_NAME' \
        < /etc/nginx/nginx.conf.template \
        > /tmp/nginx.conf

        exec nginx -c /tmp/nginx.conf -g 'daemon off;'
    networks:
      - identity-link-network

  identity-link-database-server:
    container_name: identity-link-database-server
    image: postgres:15
    restart: always
    volumes:
      - ./config/postgres:/docker-entrypoint-initdb.d:ro
    networks:
      - identity-link-network

  identity-link-redis:
    container_name: identity-link-redis
    image: redis:alpine
    networks:
      - identity-link-network

networks:
  identity-link-network:
    name: identity-link-network
    driver: bridge