services:

  identity-link-core:
    build:
      context: ./src/identity-link-core
      target: dev
    environment:
      APP_ENV: dev
      APP_SECRET: ${APP_SECRET}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_PUBLIC_KEY_PATH: /app/var/keys/public_key
      JWT_PRIVATE_KEY_PATH: /app/var/keys/private_key
      ENCRYPTION_KEY_PATH: /app/var/keys/encryption_key
    image: identity-link-core:dev
    volumes:
      - ./src/identity-link-core:/app
      - ./config/keys:/app/var/keys

  identity-link-db-users:
    build:
      context: ./src/identity-link-db-users
      target: dev
    image: identity-link-db-users:dev
    volumes:
      - ./src/identity-link-db-users:/app
    environment:
      APP_ENV: dev
      APP_SECRET: ${APP_SECRET}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      FEATURE_PASSWORD_VALIDATION_ENABLED: false
      MAILER_DSN: smtp://user%40domain.com:pass@identity-link-smtp-server:1025
      MAILER_FROM_ADDRESS: no-reply@${DOMAIN_NAME}
      MAILER_FROM_NAME: 'Identity Link'

  identity-link-db-clients:
    build:
      context: ./src/identity-link-db-clients
      target: dev
    image: identity-link-db-clients:dev
    volumes:
      - ./src/identity-link-db-clients:/app
    environment:
      APP_ENV: dev
      APP_SECRET: ${APP_SECRET}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

  identity-link-2fa:
    build:
      context: ./src/identity-link-2fa
      target: dev
    image: identity-link-2fa:dev
    volumes:
      - ./src/identity-link-2fa:/app
    environment:
      APP_ENV: dev
      APP_SECRET: ${APP_SECRET}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

  identity-link-bff:
    build:
      context: ./src/identity-link-bff
      target: dev
    image: identity-link-bff:dev
    volumes:
      - ./src/identity-link-bff:/app
      - ./runtime:/runtime
    environment:
      APP_ENV: dev
      APP_SECRET: ${APP_SECRET}
      PROXY_DEBUG: true
      HTTP_CLIENT_SSL_VERIFYPEER: 0
      HTTP_CLIENT_SSL_VERIFYHOST: 0
    entrypoint:
      - /bin/sh
      - -c
      - |
        cp /runtime/client-data.txt /app/.env.local
        exec /entrypoint.sh frankenphp run --config /etc/caddy/Caddyfile
    extra_hosts:
      - "${DOMAIN_NAME}:host-gateway"
    depends_on:
      identity-link-data-generator:
        condition: service_completed_successfully

  identity-link-console:
    build:
      context: ./src/identity-link-console
      target: dev
    image: identity-link-console:dev
    volumes:
      - ./src/identity-link-console:/app
      - /app/node_modules

  identity-link-proxy:
    volumes:
      - ./config/nginx.dev.conf.template:/etc/nginx/nginx.conf.template:ro
      - ./config/certificates/local-dev.crt:/etc/nginx/certs/server.crt:ro
      - ./config/certificates/local-dev.key:/etc/nginx/certs/server.key:ro

  identity-link-adminer:
    container_name: identity-link-adminer
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: identity-link-database-server
    ports:
      - "8080:8080"
    networks:
      - identity-link-network

  identity-link-smtp-server:
    container_name: identity-link-smtp-server
    image: mailhog/mailhog
    logging:
      driver: 'none'
    ports:
      - "8025:8025"
    networks:
      - identity-link-network

  identity-link-keys-generator:
    container_name: identity-link-keys-generator
    build:
      context: ./src/identity-link-core
      target: dev
    environment:
      APP_ENV: dev
      APP_SECRET: ${APP_SECRET}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    image: identity-link-core:dev
    entrypoint: []
    command:
      - /bin/sh
      - -c
      - |
        set -eu
        composer install --no-interaction --no-scripts --no-progress
        php bin/console identity-link:generate-encryption-key --key-path var/keys/encryption_key
        php bin/console identity-link:generate-jwt-keys --public-key-path var/keys/public_key --private-key-path var/keys/private_key
    volumes:
      - ./src/identity-link-core:/app
      - ./config/keys:/app/var/keys

  identity-link-data-generator:
    container_name: identity-link-data-generator
    image: alpine:latest
    volumes:
      - ./runtime:/runtime
      - ./bin:/scripts:ro
      - ./config/keys:/keys:ro
    environment:
      GROUP_NAME: administrator
      CLIENT_NAME: default-client
      SECRET_EXPIRATION_PERIOD: 1y
      USER_NAME: user
      USER_PASS: pass
      USER_EMAIL: test@${DOMAIN_NAME}
      REDIRECT_URIS: https://test.${DOMAIN_NAME}/auth/callback,https://${DOMAIN_NAME}/bff/login_check
      JWT_PRIVATE_KEY_PATH: /keys/private_key
      CLIENT_API_URL: https://${DOMAIN_NAME}/clients/api/v1
      USER_API_URL: https://${DOMAIN_NAME}/users/api/v1
    command:
      - /bin/sh
      - -c
      - |
        set -eu
        
        apk add --no-cache bash ca-certificates

        AUTH_TOKEN=$$(/scripts/generate-auth-token --private-key="$$JWT_PRIVATE_KEY_PATH")        
        /scripts/create-client \
          --api-url "$$CLIENT_API_URL" \
          --insecure \
          --group "$$GROUP_NAME" \
          --client "$$CLIENT_NAME" \
          --exp-period "$$SECRET_EXPIRATION_PERIOD" \
          --redirect-uris "$$REDIRECT_URIS" \
          --auth-token "$$AUTH_TOKEN" > /tmp/client_output.txt
        
        sed -n 's/^CLIENT_ID=/OIDC_CLIENT_ID=/p' /tmp/client_output.txt > /runtime/client-data.txt
        sed -n 's/^CLIENT_SECRET=/OIDC_CLIENT_SECRET=/p' /tmp/client_output.txt >> /runtime/client-data.txt
        
        /scripts/create-user \
          --api-url "$$USER_API_URL" \
          --insecure \
          --group "$$GROUP_NAME" \
          --username "$$USER_NAME" \
          --password "$$USER_PASS" \
          --email "$$USER_EMAIL" \
          --auth-token "$$AUTH_TOKEN"
    extra_hosts:
      - "${DOMAIN_NAME}:host-gateway"
    depends_on:
      identity-link-keys-generator:
        condition: service_completed_successfully
      identity-link-core:
        condition: service_healthy
      identity-link-db-users:
        condition: service_healthy
      identity-link-db-clients:
        condition: service_healthy
    networks:
      - identity-link-network

  identity-link-test-client:
    container_name: identity-link-test-client
    image: ghcr.io/beryju/oidc-test-client
    volumes:
      - ./runtime:/runtime
    environment:
      OIDC_PROVIDER: https://${DOMAIN_NAME}
      OIDC_ROOT_URL: https://test.${DOMAIN_NAME}
      OIDC_TLS_VERIFY: false
      OIDC_DO_INTROSPECTION: false
    entrypoint:
      - /bin/sh
      - -c
      - |
        set -eu

        . /runtime/client-data.txt

        export OIDC_CLIENT_ID
        export OIDC_CLIENT_SECRET

        exec /oidc-test-client
    extra_hosts:
      - "${DOMAIN_NAME}:host-gateway"
    depends_on:
      identity-link-data-generator:
        condition: service_completed_successfully
    networks:
      - identity-link-network

  identity-link-database-server:
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5