events {}

http {
    server {
        listen 80;

        # Proxy core service at root
        location / {
            proxy_pass http://host.docker.internal:9000/;
            proxy_set_header Host $host;
        }

        location /users/ {
            proxy_pass http://host.docker.internal:9001/;
            proxy_set_header Host $host;
        }

        location /clients/ {
            proxy_pass http://host.docker.internal:9002/;
            proxy_set_header Host $host;
        }

        location /2fa/ {
            proxy_pass http://host.docker.internal:9003/;
            proxy_set_header Host $host;
        }

        location /swagger/ {
            rewrite ^/swagger/(.*)$ /$1 break;
            proxy_pass http://host.docker.internal:9009/;
            proxy_set_header Host $host;
        }

        location /mail/ {
            rewrite ^/mail/(.*)$ /$1 break;
            proxy_pass http://host.docker.internal:9026/;
            proxy_set_header Host $host;
        }

        location /redis/ {
            rewrite ^/redis/(.*)$ /$1 break;
            proxy_pass http://host.docker.internal:9007/;
            proxy_set_header Host $host;
        }

        location /db/ {
            rewrite ^/db/(.*)$ /$1 break;
            proxy_pass http://host.docker.internal:9005/;
            proxy_set_header Host $host;
        }
    }
}